# Generated by Django 4.2.3 on 2023-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speed_Detection',
            fields=[
                ('SD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VIDEO', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'speed_detection',
            },
        ),
    ]
