# Generated by Django 4.2.3 on 2023-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet_Detection',
            fields=[
                ('HD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VIDEO', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'helmet_detection',
            },
        ),
    ]
