# Generated by Django 4.2.3 on 2023-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0002_helmet_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripleride_Detection',
            fields=[
                ('HD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMAGE', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'tripleride_detection',
            },
        ),
    ]
