# Generated by Django 4.2.3 on 2023-08-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0003_tripleride_detection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripleride_detection',
            old_name='HD_ID',
            new_name='TRD_ID',
        ),
    ]
