# Generated by Django 4.2.3 on 2023-08-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0004_rename_hd_id_tripleride_detection_trd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripleride_detection',
            old_name='IMAGE',
            new_name='VIDEO',
        ),
    ]
